#!/bin/bash
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l pmem=16gb
#PBS -l walltime=48:00:00
#PBS -j oe
#PBS -M mlp95@psu.edu
#PBS -N sband_test

echo "Starting job $PBS_JOBNAME"
date
echo "Job id: $PBS_JOBID"
echo "About to change into $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR
echo "About to start Python"
source activate seti
python process_gbt_data.py /gpfs/group/jtw13/default/gbt_2020/s_band/AGBT20B_999_41 --clobber
echo "Python exited"
date
