#!/bin/bash
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -M mlp95@psu.edu
#PBS -N turboseti_test

echo "Starting job $PBS_JOBNAME"
date
echo "Job id: $PBS_JOBID"
echo "About to change into $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR
echo "About to start Python"
module use ~/work/sw/modules
module load turbo_seti
turboSETI-python test.py
echo "Python exited"
date
